--- # ACL MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: get ACL infor on the /etc/test.acl.txt remote file
     acl: name=/etc/test.acl.txt entity=test etype=user state=absent
     register: var=aclinfo
