--- # COMMAND MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no
  user: test
  tasks:
  - name: Check for python packages
    command: /home/test/testing/test.sh
    args:
      chdir: /home/test/testing
