--- # FILESYSTEM MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: Format the remote data partition
     filesystem: fstype=ext3 dev=/dev/xvdf1 opts="-cc"
