--- # GIT MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: GIT clone to a remote system
     git: repo=ssh://test@jkieltyka1/home/test/playbooks dest=/home/test/gitrepo
