--- # GROUP MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: Add a new group called newgroup
     group: name=newGroup state=absent 
