--- #SSWD EXAMPLE
- hosts: apacheweb
  user: test
  become: true
  become_method: sudo
  connection: ssh
  tasks:
    - name: Adding a user to website authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test password=password owner=test2 mode=0640 
