--- # FULL INCLUDE TASKS EXAMPLE
- hosts: apacheweb
  user: test
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/package.yml
    - name: Verify telnet is installed
      raw: yum list installed| grep telnet > /home/test/pkgs.log
