--- # MAIL MODULE EXAMPLE
- hosts: apacheweb
  user: test
  connection: ssh
  gather_facts: yes
  tasks:
   - name: Send an email to test user indicating bild completion 
     mail:
       host='localhost'
       port=25
       to="test"
       subject="Our host is finished deploying"
       body='System called {{ ansible_hostname }} has been successfully deployed'
