--- # MOUNT MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: Mount the remote data partition
     mount: name=/mnt/data src=/dev/xvdf1 fstype=ext3 opts=rw state=absent  

