--- # SEBOOLEAN MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: no
  tasks:
   - name: Set httpd sebool value
     seboolean: name=httpd_anon_write state=no
