--- # Testing the J2 Template Module
- hosts: apacheweb:RedHat
  connection: ssh
  user: test
  become: true
  become_method: sudo
  gather_facts: true
  vars:
    userName: test
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the configuration file for the system
      template: src=files/test.conf.j2 dest=/home/test/test.conf owner=test group=test mode=750
