--- # TEMPLATE MODULE EXAMPLE
- hosts: apacheweb
  become: true
  become_method: sudo
  user: test
  connection: ssh
  gather_facts: yes 
  vars:
    userName: test
    userPassword: password123
    connectionType: SFTP
  tasks:
   - name: Install the custom config file
     template: src=files/test.conf.j2 dest=/home/test/test.conf owner=test group=test mode=750
