--- #THIS IS A WHEN PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: test
  become: true
  become_method: sudo
  connection: ssh
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache Appropriate to the Distributrion Type
      command: agpt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: Install Apache Appropriate to the Distributrion Type (RHEL/CentOS)
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
