--- # Master Playbook for Webservers
- hosts: apacheweb
  user: test
  become: true
  become_method: sudo
  connection: ssh
  pre_tasks:
   - name: When did the ROLE start
     raw: date > /home/test/startofrole.log
  roles:
   - webservers
  post_tasks:
   - name: When did the ROLE end
     raw: date > /home/test/endofrole.log

