--- # Install and Configure a DB server
- hosts: appserver
  user: test
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    dbserver_pkg: mariadb-server
    dbclient_pkg: mariadb
    dbserver_fqdn: jkieltyka5.mylabserver.com
    dbinstalldir: /var/lib
    dbinstancename: MyDBTest
    dbversion: 5.5.44
  tasks:
  - name: Install all the MariaDB Pkgs
    yum: pkg={{ item }} state=latest
    with_items:
    - "{{ dbserver_pkg }}"
    - "{{ dbclient_pkg }}"
    notify:
    - StartDB
    - RunInstallPause
    - RestartDB
    - CopyBkUp
    - CreateRemoteDB
    - DisplayResult
    - TestDBResults
    - ShowDBResults
  - name: Add a backup cron job to run everyday at midnight
    cron: name="DBBackup" minute="0" hour="0" job="mysqldump -u root -ppassword123 --database {{ dbinstancename }} > dbbkup.sql"
  handlers:
  - name: StartDB
    service: name={{ dbclient_pkg }} state=started
  - name: RunInstallPause
    pause: prompt="please run the mysql_secure_installation binary and then press ENTER for the playbook to continue"
  - name: RestartDB
    service: name={{ dbclient_pkg  }} state=restarted
  - name: CopyBkUp
    copy: src=files/mysqlbkup.sql dest={{ db_installdir }}/mysqlbkup.sql owner=root group=root mode=755
  - name: CreateRemoteDB
    shell: mysqladmin -u root -ppassword123 create {{ dbinstancename }}
    ignore_errors: yes
#  - name: Import tyhe db backup to the live DB
#    shell: mysql -u root -ppassword123 MyDBTest < /var/lib/mysqlbkup.sql
  - name: DisplayResult
    debug: var=result
  - name: TestDBResults
    shell: mysql -u root -ppassword123 -e 'SHOW DATABASES;'
    register: mysqlresult
  - name: ShowDBResults
    debug: var=mysqlresult
