--- # Build an apacheweb server
- hosts: apacheweb
  user: test
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    apache_pkg: httpd
    distribution: "{{ ansible_os_family }}"
    apache_version: 2.4
    apache_dir: /var/www/sample
    apache_fqdn: jkieltyka2.mylabserver.com
  tasks:
   - name: install the web server package
     yum: pkg={{ apache_pkg }} state=latest
   - name: create the web server directory
     file: path={{ apache_dir }} state=directory mode=644
   - name: copy the apache web configuration file to remote host
     copy: src=files/httpd.conf.template dest=/etc/httpd.conf owner=root group=root mode=644
   - name: create the vhost.d directory on the remote host
     file: path=/etc/httpd/vhost.d state=directory mode=644
   - name: copy and untar the source for the site
     unarchive: src=files/sitecode.tar.gz dest={{ apache_dir }}
   - name: Copy the default chost configuration
     copy: src=files/default.conf.template dest=/etc/httpd/vhost.d/default.conf owner=root group=root mode=644
     notify:
       - StartHttpd
       - TestHttpd
       - DisplayResult
  handlers:
   - name: StartHttpd
     service: name={{ apache_pkg}} state=started
   - name: TestHttpd
     shell: curl http://{{ apache_fqdn }}
     register: result
   - name: DisplayResult
     debug: var=result
     ignore_errors: yes
