- name: Install Apache Web Server (RHEL/CENOTS)
  yum: pkg={{ redhat_apache }} state=latest
  when: ansible_os_family == "RedHat"
  notify: Restart HTTPD 
- name: Install Apache Web Server (DEBIAN/UBUNTU)
  apt: pkg={{ debian_apache }}  state=latest
  when: ansible_os_family == "Debian"
  notify: Restart APACHE2
